import { createReadStream } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { Injectable, InternalServerErrorException, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { EnvironmentVariables } from '../config/env.validation';

/** Mime type → the extension we give the stored file. The client's filename is
 *  NEVER consulted for this: it is attacker-controlled. A type absent from this
 *  map is rejected before any byte is written. SVG is excluded deliberately —
 *  it is executable markup in a browser. */
export const ALLOWED_MIME_TYPES: Readonly<Record<string, string>> = {
  'application/pdf': '.pdf',
  'image/png': '.png',
  'image/jpeg': '.jpg',
  'image/gif': '.gif',
  'image/webp': '.webp',
  'text/plain': '.txt',
  'text/csv': '.csv',
  'application/msword': '.doc',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': '.docx',
  'application/vnd.ms-excel': '.xls',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': '.xlsx',
};

export interface StoredFile {
  storageKey: string;
  checksumSha256: string;
  sizeBytes: number;
}

@Injectable()
export class AttachmentStorageService {
  private readonly logger = new Logger(AttachmentStorageService.name);
  private readonly baseDir: string;

  constructor(configService: ConfigService<EnvironmentVariables, true>) {
    // Resolved ONCE, at construction. Every later path is checked against this
    // absolute prefix, so a relative UPLOAD_DIR cannot shift under a chdir.
    this.baseDir = resolve(configService.get('UPLOAD_DIR', { infer: true }));
  }

  async save(customerId: string, buffer: Buffer, mimeType: string): Promise<StoredFile> {
    const extension = ALLOWED_MIME_TYPES[mimeType];

    if (!extension) {
      // Unreachable: the service validates the type first. Failing loudly here
      // means a future caller cannot bypass the whitelist by calling save().
      throw new InternalServerErrorException('Unsupported attachment type.');
    }

    const storageKey = `customers/${customerId}/${randomUUID()}${extension}`;
    const absolute = this.resolveKey(storageKey);

    await mkdir(dirname(absolute), { recursive: true });
    await writeFile(absolute, buffer);

    return {
      storageKey,
      checksumSha256: createHash('sha256').update(buffer).digest('hex'),
      sizeBytes: buffer.byteLength,
    };
  }

  createStream(storageKey: string): ReturnType<typeof createReadStream> {
    return createReadStream(this.resolveKey(storageKey));
  }

  /** Best effort on the filesystem call only: a missing file is not an error,
   *  because the row is gone already and an orphaned file is harmless. The
   *  containment check runs OUTSIDE the try — a bad key is a bug, not a
   *  missing file, and must not be swallowed alongside ENOENT. */
  async remove(storageKey: string): Promise<void> {
    const absolute = this.resolveKey(storageKey);

    try {
      await rm(absolute, { force: true });
    } catch (error) {
      this.logger.warn({ err: error, storageKey }, 'Failed to remove attachment file');
    }
  }

  /**
   * Containment check. Keys are generated by this class, so traversal is not
   * reachable today — this is the guard that keeps it unreachable if a key ever
   * comes from the database after a manual edit, or from a future import tool.
   */
  private resolveKey(storageKey: string): string {
    const absolute = resolve(join(this.baseDir, storageKey));

    if (absolute !== this.baseDir && !absolute.startsWith(this.baseDir + sep)) {
      throw new InternalServerErrorException('Invalid attachment storage key.');
    }

    return absolute;
  }
}
